services:
  mydas:
    image: mydas:latest
    build:
      context: ..
      dockerfile: oci/Dockerfile
    platform: linux/amd64
    tty: true
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - ../src:/app/